---
- name: Развертывание Prometheus через Docker Compose
  hosts: galera_cluster
  become: yes
  vars:
    db_user: "wordpress"
    db_password: "wordpress"
    galera_cluster_name: "galera_cluster"
    backup_password: "galera_password"
    exporter_user: "exporter"
    exporter_password: "exporter"
    grafana_password: "grafana"
    compose_file_path: "/home/{{ ansible_ssh_user }}/galera_cluster/docker-compose.yml"
    galera_dir: "/home/{{ ansible_ssh_user }}/galera_cluster"
  tasks:
    - name: Проверка, что Docker запущен
      service:
        name: docker
        state: started

    - name: Создание директории для Galera Cluster
      file:
        path: "{{ galera_dir }}"
        state: directory
    - name: Копирование haproxy.cfg
      copy:
        src: "config/haproxy.cfg"
        dest: "{{ galera_dir }}/haproxy.cfg"
    - name: Создание файла конфигурации .my.cnf для mysqld_exporter_node1
      copy:
        dest: "{{ galera_dir }}/.node1.my.cnf"
        content: |
          [client]
          user={{ exporter_user }}
          password={{ exporter_password }}
          host=galera-node1
    - name: Создание файла конфигурации .my.cnf для mysqld_exporter_node2
      copy:
        dest: "{{ galera_dir }}/.node2.my.cnf"
        content: |
          [client]
          user={{ exporter_user }}
          password={{ exporter_password }}
          host=galera-node2
    - name: Создание файла конфигурации .my.cnf для mysqld_exporter_node3
      copy:
        dest: "{{ galera_dir }}/.node3.my.cnf"
        content: |
          [client]
          user={{ exporter_user }}
          password={{ exporter_password }}
          host=galera-node3
    - name: Создание файла конфигурации .my.cnf для mysqld_exporter_node4
      copy:
        dest: "{{ galera_dir }}/.node4.my.cnf"
        content: |
          [client]
          user={{ exporter_user }}
          password={{ exporter_password }}
          host=galera-node4
    - name: Создание файла конфигурации .my.cnf для mysqld_exporter_node5
      copy:
        dest: "{{ galera_dir }}/.node5.my.cnf"
        content: |
          [client]
          user={{ exporter_user }}
          password={{ exporter_password }}
          host=galera-node5

    - name: Создание пользователя для MySQL Exporter
      community.mysql.mysql_user:
        login_user: root
        login_password: "{{ db_password }}"
        login_port: 14333
        name: "{{ exporter_user }}"
        password: "{{ exporter_password }}"
        host: "%"
        priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
        state: present

    - name: Копирование datasource.yaml
      copy:
        src: "files/datasource.yml"
        dest: "{{ galera_dir }}/datasource.yml"
    - name: Копирование dashboard.json
      copy:
        src: "files/dashboard.json"
        dest: "{{ galera_dir }}/dashboard.json"
    - name: Копирование dashboard.yml
      copy:
        src: "files/dashboard.yml"
        dest: "{{ galera_dir }}/dashboard.yml"
    - name: Создание конфигурационного файла Prometheus
      copy:
        dest: "{{ galera_dir }}/prometheus.yml"
        content: |
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']
            - job_name: 'mysql_node1'
              static_configs:
                - targets: ['mysql_exporter_node1:9104']
            - job_name: 'mysql_node2'
              static_configs:
                - targets: ['mysql_exporter_node2:9104']   
            - job_name: 'mysql_node3'
              static_configs:
                - targets: ['mysql_exporter_node3:9104']           
            - job_name: 'mysql_node4'
              static_configs:
                - targets: ['mysql_exporter_node4:9104'] 
            - job_name: 'mysql_node5'
              static_configs:
                - targets: ['mysql_exporter_node5:9104']
    - name: Создание файла docker-compose.yml
      copy:
        dest: "{{ compose_file_path }}"
        content: |
          version: '3'
          services:
            galera-node1:
              image: rancher/galera:10.0.22-rancher2
              environment:
                MYSQL_ROOT_PASSWORD: {{ db_password }}
                MYSQL_DATABASE: wordpress
                MYSQL_USER: {{ db_user }}
                MYSQL_PASSWORD: {{ db_password }}
                CLUSTER_NAME: {{ galera_cluster_name }}
                XTRABACKUP_PASSWORD: {{ backup_password }}
                WSREP_NODE_NAME: galera-node1
                WSREP_NODE_ADDRESS: galera-node1
                WSREP_CLUSTER_ADDRESS: "gcomm://galera-node1,galera-node2,galera-node3,galera-node4,galera-node5"
              ports:
                - "3310:3306"
              networks:
                - local_network
          
            galera-node2:
              image: rancher/galera:10.0.22-rancher2
              environment:
                MYSQL_ROOT_PASSWORD: {{ db_password }}
                MYSQL_DATABASE: wordpress
                MYSQL_USER: {{ db_user }}
                MYSQL_PASSWORD: {{ db_password }}
                CLUSTER_NAME: {{ galera_cluster_name }}
                XTRABACKUP_PASSWORD: {{ backup_password }}
                WSREP_NODE_NAME: galera-node2
                WSREP_NODE_ADDRESS: galera-node2
                WSREP_CLUSTER_ADDRESS: "gcomm://galera-node1,galera-node2,galera-node3,galera-node4,galera-node5"
              ports:
                - "3311:3306"
              networks:
                - local_network
          
            galera-node3:
              image: rancher/galera:10.0.22-rancher2
              environment:
                MYSQL_ROOT_PASSWORD: {{ db_password }}
                MYSQL_DATABASE: wordpress
                MYSQL_USER: {{ db_user }}
                MYSQL_PASSWORD: {{ db_password }}
                CLUSTER_NAME: {{ galera_cluster_name }}
                XTRABACKUP_PASSWORD: {{ backup_password }}
                WSREP_NODE_NAME: galera-node3
                WSREP_NODE_ADDRESS: galera-node3
                WSREP_CLUSTER_ADDRESS: "gcomm://galera-node1,galera-node2,galera-node3,galera-node4,galera-node5"
              ports:
                - "3312:3306"
              networks:
                - local_network
          
            galera-node4:
              image: rancher/galera:10.0.22-rancher2
              environment:
                MYSQL_ROOT_PASSWORD: {{ db_password }}
                MYSQL_DATABASE: wordpress
                MYSQL_USER: {{ db_user }}
                MYSQL_PASSWORD: {{ db_password }}
                CLUSTER_NAME: {{ galera_cluster_name }}
                XTRABACKUP_PASSWORD: {{ backup_password }}
                WSREP_NODE_NAME: galera-node4
                WSREP_NODE_ADDRESS: galera-node4
                WSREP_CLUSTER_ADDRESS: "gcomm://galera-node1,galera-node2,galera-node3,galera-node4,galera-node5"
              ports:
                - "3313:3306"
              networks:
                - local_network     
          
            galera-node5:
              image: rancher/galera:10.0.22-rancher2
              environment:
                MYSQL_ROOT_PASSWORD: {{ db_password }}
                MYSQL_DATABASE: wordpress
                MYSQL_USER: {{ db_user }}
                MYSQL_PASSWORD: {{ db_password }}
                CLUSTER_NAME: {{ galera_cluster_name }}
                XTRABACKUP_PASSWORD: {{ backup_password }}
                WSREP_NODE_NAME: galera-node5
                WSREP_NODE_ADDRESS: galera-node5
                WSREP_CLUSTER_ADDRESS: "gcomm://galera-node1,galera-node2,galera-node3,galera-node4,galera-node5"
              ports:
                - "3314:3306"
              networks:
                - local_network      
            haproxy:
              image: haproxy:latest
              ports:
                - "14333:14333" # frontend
                - "13333:13333" # statistic 
              volumes:
                - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
                - haproxy:/usr/local/etc/haproxy
              networks:
                - local_network   
            wordpress:
              image: wordpress:latest
              restart: always
              ports:
                - "8080:80"
              environment:
                WORDPRESS_DB_HOST: "haproxy:14333"
                WORDPRESS_DB_NAME: "wordpress"
                WORDPRESS_DB_USER: "{{ db_user }}"
                WORDPRESS_DB_PASSWORD: "{{ db_password }}"
              volumes:
                - wordpress:/var/www/html
              networks:
                - local_network 
            prometheus:
              image: prom/prometheus
              volumes:
                - ./prometheus.yml:/etc/prometheus/prometheus.yml
              ports:
                - "9090:9090"
              networks:
                - local_network
            mysql_exporter_node1:
              image: prom/mysqld-exporter
              volumes:
                - {{ galera_dir }}/.node1.my.cnf:/etc/.my.cnf:ro
              command: ["--config.my-cnf=/etc/.my.cnf"]          
              ports:
                - "9104:9104"
              networks:
                - local_network
            mysql_exporter_node2:
              image: prom/mysqld-exporter
              volumes:
                - {{ galera_dir }}/.node2.my.cnf:/etc/.my.cnf:ro
              command: ["--config.my-cnf=/etc/.my.cnf"]          
              ports:
                - "9105:9104"
              networks:
                - local_network
            mysql_exporter_node3:
              image: prom/mysqld-exporter
              volumes:
                - {{ galera_dir }}/.node3.my.cnf:/etc/.my.cnf:ro
              command: ["--config.my-cnf=/etc/.my.cnf"]          
              ports:
                - "9106:9104"
              networks:
                - local_network
            mysql_exporter_node4:
              image: prom/mysqld-exporter
              volumes:
                - {{ galera_dir }}/.node4.my.cnf:/etc/.my.cnf:ro
              command: ["--config.my-cnf=/etc/.my.cnf"]          
              ports:
                - "9107:9104"
              networks:
                - local_network
            mysql_exporter_node5:
              image: prom/mysqld-exporter
              volumes:
                - {{ galera_dir }}/.node5.my.cnf:/etc/.my.cnf:ro
              command: ["--config.my-cnf=/etc/.my.cnf"]          
              ports:
                - "9108:9104"
              networks:
                - local_network
            grafana:
              image: grafana/grafana
              ports:
                - "3000:3000"
              depends_on:
                - prometheus
              environment:
                - GF_SECURITY_ADMIN_PASSWORD={{ grafana_password }}
              volumes:
                - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml 
                - ./dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json 
                - ./dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml 
              networks:
                - local_network          
          volumes:
            wordpress:
            haproxy:
          networks:
            local_network:
              external: true
    - name: Создание пользователя для MySQL Exporter
      community.mysql.mysql_user:
        login_user: root
        login_password: "{{ db_password }}"
        login_port: 14333
        name: "{{ exporter_user }}"
        password: "{{ exporter_password }}"
        host: "%"
        priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
        state: present

    - name: Запуск Docker образов
      community.docker.docker_compose_v2:
        project_src: "{{ galera_dir }}"
        files: "{{ compose_file_path }}"
