---
- name: Deploy WordPress with MySQL
  hosts: wordpress
  become: yes
  vars:
    db_user: "wordpress"
    db_password: "wordpress"
    compose_file_path: "/home/{{ ansible_ssh_user }}/wordpress/docker-compose.yml"
    wordpress_dir: "/home/{{ ansible_ssh_user }}/wordpress"
    
  tasks:
    - name: Create WordPress directory
      file:
        path: "{{ wordpress_dir }}"
        state: directory
        mode: '0755'

    - name: Configure Docker Compose file
      copy:
        dest: "{{ compose_file_path }}"
        content: |
          version: '3'
          services:
            db_master:
              image: mysql:5.7
              restart: always
              environment:
                MYSQL_ROOT_PASSWORD: "{{ db_password }}"
                MYSQL_DATABASE: wordpress
                MYSQL_USER: "{{ db_user }}"
                MYSQL_PASSWORD: "{{ db_password }}"
              ports:
                - "3306:3306"             
              command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
              volumes:
                - db_master:/var/lib/mysql
              networks:
                - local_network
            db_slave:
              image: mysql:5.7
              restart: always
              environment:
                MYSQL_ROOT_PASSWORD: "{{ db_password }}"
                MYSQL_DATABASE: wordpress
                MYSQL_USER: "{{ db_user }}"
                MYSQL_PASSWORD: "{{ db_password }}"
              ports:
                - "3307:3306"             
              command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
              volumes:
                - db_slave:/var/lib/mysql
              networks:
                - local_network          
            wordpress:
              image: wordpress:latest
              restart: always
              ports:
                - "8080:80"
              depends_on:
                - db_master
                - db_slave
              environment:
                WORDPRESS_DB_HOST: db_master
                WORDPRESS_DB_USER: "{{ db_user }}"
                WORDPRESS_DB_PASSWORD: "{{ db_password }}"
              volumes:
                - wordpress:/var/www/html
              networks:
                - local_network
          
          networks:
            local_network:
              external: true
          volumes:
            db_master:
            wordpress:
            db_slave:

    - name: Start MySQL services
      community.docker.docker_compose_v2:
        project_src: "{{ wordpress_dir }}"
        services:
          - db_master
          - db_slave
      
    - name: Проверка доступности MySQL
      community.mysql.mysql_info:
        login_port: 3306
        login_user: root
        login_password: "{{ db_password }}"
      register: mysql_check
      retries: 30
      delay: 3
    - name: Проверка доступности MySQL
      community.mysql.mysql_info:
        login_port: 3307
        login_user: root
        login_password: "{{ db_password }}"
      register: mysql_check
      retries: 30
      delay: 3


    - name: Create replication user on Master
      mysql_query:
        login_port: 3306
        login_user: "root"
        login_password: "{{ db_password }}"
        query: "CREATE USER IF NOT EXISTS 'replication'@'%' IDENTIFIED WITH mysql_native_password BY 'replication';"

    - name: Grant replication privileges
      mysql_query:
        login_port: 3306
        login_user: "root"
        login_password: "{{ db_password }}"
        query: "GRANT REPLICATION SLAVE ON *.* TO 'replication'@'%';"

    - name: Flush privileges
      mysql_query:
        login_port: 3306
        login_user: "root"
        login_password: "{{ db_password }}"
        query: "FLUSH PRIVILEGES;"

    - name: Show master status
      mysql_query:
        login_port: 3306
        login_user: "root"
        login_password: "{{ db_password }}"
        query: "SHOW MASTER STATUS;"
      register: master_status
      
    - name: Debug master_status
      debug:
        var: master_status
    - name: Задать данные для репликации
      mysql_replication:
        login_user: "root"
        login_password: "{{ db_password }}"
        login_port: 3307
        mode: changeprimary
        master_host: db_master
        master_user: replication
        master_password: replication
        master_log_file: "{{ master_status.query_result[0][0].File }}"
        master_log_pos: "{{ master_status.query_result[0][0].Position }}"
    
    - name: Start Slave on Replica
      mysql_query:
        login_port: 3307
        login_user: "root"
        login_password: "{{ db_password }}"
        query: "START SLAVE;"

    - name: Start WordPress
      community.docker.docker_compose_v2:
        project_src: "{{ wordpress_dir }}"
        services:
          - wordpress

    - name: Wait for WordPress to be accessible
      wait_for:
        port: 8080
        delay: 10
        timeout: 60
