[wordpress]
51.250.43.36  ansible_ssh_user=margo
   
[prometheus_servers]
51.250.43.36  ansible_ssh_user=margo
#192.168.223.1 ansible_user=main ansible_ssh_port=2222 ansible_become=yes ansible_password=Ewq21412
[galera_cluster]
51.250.43.36 ansible_ssh_user=margo